lesson_list={"input":[
{"The cell membrane has a specific structure and function":{"rating":78,"data":[{"item":"The cell membrane has a specific structure and function","attributes":["cellular_structure","transport","homeostasis"],"answer":True}]}},
{"Mitochondria produce energy in a cell":{"rating":82,"data":[{"item":"Mitochondria produce energy in a cell","attributes":["energy_production","metabolism"],"answer":True}]}},
{"Photosynthesis occurs in animal cells to produce energy":{"rating":74,"data":[{"item":"Photosynthesis occurs in animal cells to produce energy","attributes":["energy_production","metabolism"],"answer":False}]}},
{"Enzymes slow down chemical reactions in biology":{"rating":69,"data":[{"item":"Enzymes slow down chemical reactions in biology","attributes":["molecular_function","metabolism"],"answer":False}]}},
{"DNA replication occurs in cells":{"rating":63,"data":[{"item":"DNA replication occurs in cells","attributes":["genetic_information","information_transfer"],"answer":True}]}},
{"RNA transcription is a biological process":{"rating":66,"data":[{"item":"RNA transcription is a biological process","attributes":["genetic_information","information_transfer"],"answer":True}]}},
{"Protein synthesis occurs through translation":{"rating":71,"data":[{"item":"Protein synthesis occurs through translation","attributes":["molecular_function","information_transfer"],"answer":True}]}},
{"Mitosis creates genetic variation between gametes":{"rating":85,"data":[{"item":"Mitosis creates genetic variation between gametes","attributes":["growth_and_development","reproduction"],"answer":False}]}},
{"Meiosis creates genetic variation":{"rating":88,"data":[{"item":"Meiosis creates genetic variation","attributes":["genetic_information","adaptation","reproduction"],"answer":True}]}},
{"The cell cycle has important phases":{"rating":76,"data":[{"item":"The cell cycle has important phases","attributes":["growth_and_development","regulation"],"answer":True}]}},
{"Osmosis and diffusion require cellular energy":{"rating":99,"data":[{"item":"Osmosis and diffusion require cellular energy","attributes":["transport","homeostasis"],"answer":False}]}},
{"Active transport differs from passive transport":{"rating":83,"data":[{"item":"Active transport differs from passive transport","attributes":["transport","energy_production"],"answer":True}]}},
{"Homeostasis maintains internal balance":{"rating":79,"data":[{"item":"Homeostasis maintains internal balance","attributes":["homeostasis","regulation"],"answer":True}]}},
{"The immune system responds only to viruses":{"rating":61,"data":[{"item":"The immune system responds only to viruses","attributes":["system_interaction","adaptation"],"answer":False}]}},
{"The nervous system has specific components and functions":{"rating":77,"data":[{"item":"The nervous system has specific components and functions","attributes":["regulation","information_transfer"],"answer":True}]}},
{"The endocrine system regulates body functions":{"rating":72,"data":[{"item":"The endocrine system regulates body functions","attributes":["regulation","system_interaction"],"answer":True}]}},
{"The respiratory system enables gas exchange":{"rating":94,"data":[{"item":"The respiratory system enables gas exchange","attributes":["transport","system_interaction"],"answer":True}]}},
{"The circulatory system only transports oxygen":{"rating":64,"data":[{"item":"The circulatory system only transports oxygen","attributes":["transport","system_interaction"],"answer":False}]}},
{"Digestive enzymes break down food":{"rating":75,"data":[{"item":"Digestive enzymes break down food","attributes":["metabolism","molecular_function"],"answer":True}]}},
{"The excretory system removes waste":{"rating":60,"data":[{"item":"The excretory system removes waste","attributes":["homeostasis","system_interaction"],"answer":True}]}},
{"Xylem and phloem transport materials in plants":{"rating":81,"data":[{"item":"Xylem and phloem transport materials in plants","attributes":["transport","cellular_structure"],"answer":True}]}},
{"Energy flows through ecosystems":{"rating":84,"data":[{"item":"Energy flows through ecosystems","attributes":["ecological_process","energy_production"],"answer":True}]}},
{"Population growth is influenced by multiple factors":{"rating":73,"data":[{"item":"Population growth is influenced by multiple factors","attributes":["ecological_process","adaptation"],"answer":True}]}},
{"Natural selection plays no role in evolution":{"rating":72,"data":[{"item":"Natural selection plays no role in evolution","attributes":["adaptation","genetic_information"],"answer":False}]}},
{"Genetic mutations create variation":{"rating":65,"data":[{"item":"Genetic mutations create variation","attributes":["genetic_information","adaptation"],"answer":True}]}},
{"Dominant alleles always eliminate recessive alleles":{"rating":67,"data":[{"item":"Dominant alleles always eliminate recessive alleles","attributes":["genetic_information"],"answer":False}]}},
{"Punnett squares are used to analyze inheritance":{"rating":70,"data":[{"item":"Punnett squares are used to analyze inheritance","attributes":["genetic_information","information_transfer"],"answer":True}]}},
{"Biotechnology uses specialized tools":{"rating":84,"data":[{"item":"Biotechnology uses specialized tools","attributes":["molecular_function","information_transfer"],"answer":True}]}},
{"Ecological succession changes communities":{"rating":87,"data":[{"item":"Ecological succession changes communities","attributes":["ecological_process","adaptation"],"answer":True}]}},
{"Human reproduction follows biological processes":{"rating":75,"data":[{"item":"Human reproduction follows biological processes","attributes":["reproduction","growth_and_development"],"answer":True}]}},
{"Plants reproduce through specific processes":{"rating":71,"data":[{"item":"Plants reproduce through specific processes","attributes":["reproduction","growth_and_development"],"answer":True}]}},
{"Cells specialize into tissues":{"rating":82,"data":[{"item":"Cells specialize into tissues","attributes":["growth_and_development","regulation"],"answer":True}]}},
{"Stem cells have unique functions":{"rating":80,"data":[{"item":"Stem cells have unique functions","attributes":["growth_and_development","cellular_structure"],"answer":True}]}},
{"Bacteria develop antibiotic resistance":{"rating":60,"data":[{"item":"Bacteria develop antibiotic resistance","attributes":["adaptation","genetic_information"],"answer":True}]}},
{"Viruses are made of cells":{"rating":76,"data":[{"item":"Viruses are made of cells","attributes":["cellular_structure","information_transfer"],"answer":False}]}},
{"Bacterial cells share common characteristics":{"rating":71,"data":[{"item":"Bacterial cells share common characteristics","attributes":["cellular_structure"],"answer":True}]}},
{"Eukaryotic cells lack a nucleus":{"rating":67,"data":[{"item":"Eukaryotic cells lack a nucleus","attributes":["cellular_structure","genetic_information"],"answer":False}]}},
{"The scientific method applies to biology":{"rating":72,"data":[{"item":"The scientific method applies to biology","attributes":["information_transfer"],"answer":True}]}}
],"rules":"rating","length":10}




lesson_ratings = {
  "cellular_structure": 91,
  "transport": 88,
  "homeostasis": 84,
  "energy_production": 95,
  "metabolism": 82,
  "molecular_function": 90,
  "genetic_information": 93,
  "information_transfer": 86,
  "growth_and_development": 89,
  "reproduction": 87,
  "regulation": 85,
  "system_interaction": 83,
  "adaptation": 92,
  "ecological_process": 94
}
